using System.Globalization;

namespace Art3m1s.PsvTool.App;

public interface ILocalizer
{
    string Language { get; }
    string this[string key] { get; }
    void SetLanguage(string language);
    event EventHandler? LanguageChanged;
}

public sealed class Localizer : ILocalizer
{
    private static readonly IReadOnlyDictionary<string, string> Zh = new Dictionary<string, string>
    {
        ["Title"] = "art3m1s PSV 移植工具",
        ["Subtitle"] = "Artemis 游戏资源缩小与 PFS 重打包",
        ["Project"] = "项目",
        ["AssetRightsBackupWarning"] = "请只处理你有权修改的游戏资源，并先备份原项目。",
        ["Input"] = "输入目录",
        ["Output"] = "输出目录",
        ["Browse"] = "浏览…",
        ["Scan"] = "扫描项目",
        ["AutoScanResolution"] = "自动扫描分辨率",
        ["ResolutionList"] = "system.ini 中的分辨率（点击选择预览）",
        ["IniPreamble"] = "无段落",
        ["ResolutionDetected"] = "已识别原始分辨率：{0}",
        ["ResolutionNotFound"] = "未在 system.ini 中找到有效宽高。",
        ["ScanEmpty"] = "等待扫描 PFS 文件",
        ["Ratio"] = "缩小比例",
        ["RatioHelp"] = "按游戏分辨率设置；自动扫描会重算 Ratio，以保持比例适配 960×540，且不放大。手动切换分辨率列表只更新预览。设置过大可能导致 PSV 内存不足；PSB 独立 Ratio 不受此处影响。",
        ["Original"] = "原始分辨率",
        ["Target"] = "预计输出",
        ["Unknown"] = "未知",
        ["Types"] = "处理类型",
        ["Text"] = "文本（INI / TBL / IPT / AST / LUA）",
        ["Images"] = "图片（PNG）",
        ["Animation"] = "动画（OGV / E-mote PSB）",
        ["Video"] = "视频（WMV / DAT / MP4 / AVI / MPG / MKV）",
        ["FontSubset"] = "字体削减（TTF / OTF）",
        ["FontSubsetHelp"] = "保留脚本实际字符、常用符号及所选语言常用字；支持 TrueType 与 CFF OpenType，TTC 原样保留。",
        ["Simplified"] = "简体中文",
        ["Japanese"] = "日文",
        ["Traditional"] = "繁体中文",
        ["Mode"] = "图片缩放与可选纹理压缩",
        ["ModeHelp"] = "图片使用 Alpha 预乘的高质量 Bicubic 缩小；原格式 PNG 不执行优化、调色板压缩或 waifu2x；下方可独立启用 PSV 有损纹理压缩。",
        ["Advanced"] = "高级设置",
        ["Parallel"] = "并行任务",
        ["Auto"] = "自动",
        ["Encoding"] = "PFS 路径编码",
        ["IgnorePfsVideos"] = "忽略 PFS 内的视频（WMV / DAT / MP4 / AVI / MPG / MKV）",
        ["ConvertEmotePsbTexturesToDxt5"] = "E-mote PSB 纹理转 DXT5（BC3）",
        ["ConvertEmotePsbTexturesToDxt5Help"] = "缩放后将内嵌 RGBA8 图集转为 DXT5（BC3）：同尺寸数据约为 RGBA8 的 1/4，保留渐变透明但属于有损压缩。支持原生 BC3 的引擎可直接采样，减少显存与传输量；具体对齐占用见上方 PSB 分组说明。不写入 DDS 头或 PSV swizzle。",
        ["PsbTitle"] = "PSB 贴图分辨率与独立缩放",
        ["PsbScan"] = "扫描 PSB 贴图",
        ["PsbHelp"] = "扫描 PFS 内和散装 PSB，按最大贴图的宽 × 高分类（多图集按面积最大的贴图归类）。独立缩放默认关闭，PSB 跟随全局 Ratio。开启后每类贴图 Ratio 默认 0.5，只改变贴图与 UV 矩形；坐标、origin 和画布仍跟随全局 Ratio。需勾选动画处理；DXT5 开关独立控制格式压缩。",
        ["IndependentPsbTextureScaling"] = "PSB 贴图分辨率单独缩放（默认关闭）",
        ["PsbRenderCompensation"] = "PSB 渲染补偿比例（全局 Ratio ÷ 贴图 Ratio = 补偿倍数）",
        ["PsbCompensationPreview"] = "渲染补偿 {0}×（全局 {1} ÷ 贴图 {2}）",
        ["PsbCompensationOff"] = "渲染补偿：未启用",
        ["PsbRenderCompensationHelp"] = "默认勾选，仅在启用 PSB 独立缩放并处理动画时生效。输出 art3m1s_psb_render.json，需支持此配置的 GXM 引擎；只补偿部件绘制尺寸，不再次放大坐标或改变 UV。关闭补偿不输出该配置，人物大小可能不匹配。",
        ["PsbCount"] = "{0} 个 PSB · {1} 张贴图",
        ["PsbEmptyHelp"] = "点击“扫描 PSB 贴图”后，仅显示实际发现的尺寸及 Ratio；已有配置按尺寸恢复，新尺寸默认 0.5。",
        ["PsbDxt5Title"] = "DXT5 显存占用与压缩原因（有损，支持渐变透明）",
        ["PsbDxt5Help"] = "RGBA8 每像素 4 字节；DXT5 / BC3 每 4×4 像素占 16 字节（约每像素 1 字节），支持渐变透明。比如 4096×2048：RGBA8 数据 32 MiB，DXT5 数据 8 MiB；Ratio 0.5 后为 2048×1024，DXT5 数据 2 MiB。\n\n它不仅缩小资源文件：当前 Art3m1sPSV 的原生 BC3 路径直接用压缩纹理渲染，无需完整 RGBA 像素副本，可减少显存和传输量。代价是有损的颜色与透明度近似，不能保证提升帧率；若引擎回退为 RGBA 解码，显存收益可能消失。\n\n每行只比较该类最大图集在所选 Ratio 下的 RGBA8 / DXT5 纹理分配，不是整份 PSB 或游戏总显存，也不随格式开关隐藏。当前 GXM：DXT5 宽高分别向上补至 2 的幂（最小 4）；RGBA 行宽对齐至 8 像素；两者单次分配均向上对齐 256 KiB。因此 3072×1536 的 DXT5 数据虽为 4.5 MiB，分配估计为 8 MiB；小贴图两种格式都可能占 0.25 MiB。多图集按实际同时加载的贴图逐张累加，另有缓存、渲染目标和临时内存开销。1 MiB = 1024×1024 字节。",
        ["PsbMemoryComparison"] = "缩放后最大图集分配估计：RGBA8 {0} MiB / DXT5 {1} MiB · DXT5 数据 {2} MiB",
        ["PsbMemoryUnsupported"] = "缩放后尺寸超过当前 PSV 原生 BC3 路径的 4096 上限，不估算显存。",
        ["PsbDetails"] = "查看文件与全部贴图尺寸",
        ["PsbInvalidRatio"] = "PSB Ratio 必须是大于 0、不超过 1 的数字。",
        ["PsbScanSummary"] = "已扫描 {0} 个 PSB / {1} 类尺寸 / {2} 个未归类（详见日志）",
        ["PsbInputChanged"] = "输入目录已改变，请重新扫描 PSB。",
        ["ScanInputChanged"] = "输入目录已改变，请重新扫描。",
        ["PsbNoAtlas"] = "非 E-mote 或无内嵌贴图",
        ["Log"] = "运行日志",
        ["Ready"] = "准备就绪",
        ["Start"] = "开始转换",
        ["Cancel"] = "取消",
        ["About"] = "关于",
        ["ProjectRepository"] = "项目 GitHub",
        ["AboutBody"] = "本程序采用 GPL-3.0-or-later，不提供任何担保。\n\nCredits\npfs_upk · GPL-3.0 · PFS 格式与行为参考\nart3m1s-core · MPL-2.0 · E-mote PSB 结构、加密头与资源表参考\nVisualNovelUpscaler · MIT · Artemis 文本与 Ratio 规则参考\nAvalonia 12.1.2 · MIT · 跨平台 UI\nSixLabors.ImageSharp 3.1.12 · Six Labors Split License 1.0 · PNG 处理\nPVRTexLib.NET 1.0.3 · MIT · PSV texture encoding\nThis product includes components of the PowerVR Tools Software from Imagination Technologies Limited.\nHarfBuzz 8.3.1 · Old MIT · CFF OpenType 字体削减\nOptris.StaticGraphics.Avalonia.Software 3.119.4.1 · MIT 及上游许可 · NativeAOT 图形后端\nFFmpeg / ffprobe n9.0 · GPL Full 构建 · 独立程序\nBtbN/FFmpeg-Builds · GPL-3.0 · Windows/Linux 静态二进制\ndav1d · BSD-2-Clause · AV1 软件解码\nx264 · GPL-2.0 · H.264 编码\nlibtheora · BSD-3-Clause · Theora 编码\nlibogg · BSD-3-Clause · Ogg 容器\nzlib · Zlib · PNG 帧序列压缩\n\nwith-ffmpeg 发行包的 Full 构建位于 tools 目录，不嵌入主程序且不包含 nonfree 组件；no-ffmpeg 包需要用户自行配置。正式发布包的 licenses 目录包含第三方许可证；对应源码、构建配置及校验信息随 Release 提供。",
        ["Theme"] = "主题",
        ["Dark"] = "深色",
        ["Light"] = "浅色",
        ["Archives"] = "个独立 PFS",
        ["InvalidPaths"] = "请选择有效且不同的输入、输出目录。",
        ["Overwrite"] = "输出目录已存在；再次点击开始将覆盖。",
        ["Finished"] = "转换完成",
        ["Failed"] = "转换失败",
        ["FailureDetails"] = "失败详情",
        ["ErrorArchive"] = "PFS 归档",
        ["ErrorFile"] = "错误文件",
        ["ErrorReason"] = "错误原因",
        ["Scanning"] = "正在扫描…",
        ["NoPfs"] = "未找到有效 PFS。",
        ["StageCopy"] = "正在复制项目文件…",
        ["StageExtract"] = "正在解包 PFS…",
        ["StagePack"] = "正在重新打包 PFS…",
        ["StageLoose"] = "正在处理散装资源…",
        ["StageResource"] = "正在转换资源…",
        ["StageComplete"] = "转换完成",
        ["DemoProgress"] = "正在转换 {0} · {1}%"
    };

    private static readonly IReadOnlyDictionary<string, string> En = new Dictionary<string, string>
    {
        ["Title"] = "art3m1s PSV Port Tool",
        ["Subtitle"] = "Resize Artemis game assets and rebuild independent PFS archives",
        ["Project"] = "Project",
        ["AssetRightsBackupWarning"] = "Only process game assets you are authorized to modify, and back up the original project first.",
        ["Input"] = "Input folder",
        ["Output"] = "Output folder",
        ["Browse"] = "Browse…",
        ["Scan"] = "Scan project",
        ["AutoScanResolution"] = "Detect resolution",
        ["ResolutionList"] = "Resolutions in system.ini (select to preview)",
        ["IniPreamble"] = "Unsectioned",
        ["ResolutionDetected"] = "Original resolution detected: {0}",
        ["ResolutionNotFound"] = "No valid width and height found in system.ini.",
        ["ScanEmpty"] = "Waiting to scan PFS files",
        ["Ratio"] = "Resize ratio",
        ["RatioHelp"] = "Detect resolution recalculates Ratio to fit 960×540 without changing aspect ratio or upscaling. Manually choosing a resolution only changes the preview. Larger output may exceed PSV memory; independent PSB ratios are unaffected.",
        ["Original"] = "Original resolution",
        ["Target"] = "Estimated output",
        ["Unknown"] = "Unknown",
        ["Types"] = "Asset types",
        ["Text"] = "Text (INI / TBL / IPT / AST / LUA)",
        ["Images"] = "Images (PNG)",
        ["Animation"] = "Animation (OGV / E-mote PSB)",
        ["Video"] = "Video (WMV / DAT / MP4 / AVI / MPG / MKV)",
        ["FontSubset"] = "Font subsetting (TTF / OTF)",
        ["FontSubsetHelp"] = "Keeps characters used by scripts, common symbols, and the selected language set. TrueType and CFF OpenType are supported; TTC stays unchanged.",
        ["Simplified"] = "Simplified Chinese",
        ["Japanese"] = "Japanese",
        ["Traditional"] = "Traditional Chinese",
        ["Mode"] = "Image resizing and optional texture compression",
        ["ModeHelp"] = "Images use high-quality alpha-premultiplied Bicubic resizing; no PNG optimization, palette compression, or waifu2x.",
        ["Advanced"] = "Advanced",
        ["Parallel"] = "Parallel tasks",
        ["Auto"] = "Auto",
        ["Encoding"] = "PFS path encoding",
        ["IgnorePfsVideos"] = "Ignore video inside PFS (WMV / DAT / MP4 / AVI / MPG / MKV)",
        ["ConvertEmotePsbTexturesToDxt5"] = "Convert E-mote PSB textures to DXT5 (BC3)",
        ["ConvertEmotePsbTexturesToDxt5Help"] = "Converts resized RGBA8 atlases to DXT5 (BC3): approximately one quarter of RGBA8 data at the same dimensions, with interpolated alpha and lossy compression. Native BC3 sampling can reduce GPU memory and transfers; see the PSB section for alignment estimates. No DDS header or PSV swizzle is added.",
        ["PsbTitle"] = "PSB texture dimensions and independent resize",
        ["PsbScan"] = "Scan PSB textures",
        ["PsbHelp"] = "Scan loose/archived PSBs by the largest atlas width × height. Independent resizing is off by default: PSBs follow the global Ratio. When enabled, per-group texture ratios default to 0.5 and affect only atlases and UV rectangles; coordinates, origins and canvas still follow the global Ratio. Enable Animation processing to resize; DXT5 compression is separate.",
        ["IndependentPsbTextureScaling"] = "Resize PSB textures independently (off by default)",
        ["PsbRenderCompensation"] = "PSB render compensation (global Ratio ÷ texture Ratio = multiplier)",
        ["PsbCompensationPreview"] = "Render compensation {0}× (global {1} ÷ texture {2})",
        ["PsbCompensationOff"] = "Render compensation: inactive",
        ["PsbRenderCompensationHelp"] = "Checked by default; applies only with independent PSB resizing and Animation processing. Outputs art3m1s_psb_render.json for a compatible GXM engine. Compensates part dimensions without rescaling coordinates or UVs. Unchecking omits this file and may produce incorrect portrait sizes.",
        ["PsbCount"] = "{0} PSB files · {1} textures",
        ["PsbEmptyHelp"] = "Click “Scan PSB textures” to list only discovered dimensions and ratios. Saved ratios are restored by dimensions; new sizes default to 0.5.",
        ["PsbDxt5Title"] = "DXT5 GPU memory and why compress (lossy, interpolated alpha)",
        ["PsbDxt5Help"] = "RGBA8 uses 4 bytes per pixel; DXT5 / BC3 uses 16 bytes per 4×4 block (approximately 1 byte per pixel) and supports interpolated alpha. A 4096×2048 atlas uses 32 MiB of RGBA8 data or 8 MiB of DXT5 data; Ratio 0.5 produces 2048×1024 with 2 MiB of DXT5 data.\n\nThis is more than smaller files: the current Art3m1sPSV native BC3 path renders compressed textures directly without a full RGBA pixel mirror, reducing GPU storage and transfers. Color and alpha are approximated lossily; higher frame rates are not guaranteed. Falling back to RGBA decoding may remove the GPU-memory benefit.\n\nEach row compares the group's largest atlas at the selected Ratio, not the entire PSB or total game memory, regardless of the format toggle. Current GXM storage rounds BC3 dimensions up to powers of two (minimum 4), aligns RGBA row stride to 8 pixels, and rounds each allocation up to 256 KiB. Thus 3072×1536 DXT5 has 4.5 MiB of data but an estimated 8 MiB allocation; small textures may cost 0.25 MiB in either format. Sum the atlases actually loaded together; caches, render targets and temporary memory are extra. 1 MiB = 1024×1024 bytes.",
        ["PsbMemoryComparison"] = "Resized largest-atlas allocation estimate: RGBA8 {0} MiB / DXT5 {1} MiB · DXT5 data {2} MiB",
        ["PsbMemoryUnsupported"] = "Resized dimensions exceed the current native PSV BC3 limit of 4096; GPU memory is not estimated.",
        ["PsbDetails"] = "Show files and all texture dimensions",
        ["PsbInvalidRatio"] = "PSB Ratio must be a number greater than 0 and no greater than 1.",
        ["PsbScanSummary"] = "Scanned {0} PSB files / {1} dimension groups / {2} unclassified (see log)",
        ["PsbInputChanged"] = "Input folder changed; scan PSB files again.",
        ["ScanInputChanged"] = "Input folder changed; scan again.",
        ["PsbNoAtlas"] = "Not E-mote or no embedded textures",
        ["Log"] = "Run log",
        ["Ready"] = "Ready",
        ["Start"] = "Start conversion",
        ["Cancel"] = "Cancel",
        ["About"] = "About",
        ["ProjectRepository"] = "Project GitHub",
        ["AboutBody"] = "This program is GPL-3.0-or-later and comes with no warranty.\n\nCredits\npfs_upk · GPL-3.0 · PFS format and behavior reference\nart3m1s-core · MPL-2.0 · E-mote PSB structure, encrypted-header, and resource-table reference\nVisualNovelUpscaler · MIT · Artemis text and Ratio rule reference\nAvalonia 12.1.2 · MIT · Cross-platform UI\nSixLabors.ImageSharp 3.1.12 · Six Labors Split License 1.0 · PNG processing\nPVRTexLib.NET 1.0.3 · MIT · PSV texture encoding\nThis product includes components of the PowerVR Tools Software from Imagination Technologies Limited.\nHarfBuzz 8.3.1 · Old MIT · CFF OpenType font subsetting\nOptris.StaticGraphics.Avalonia.Software 3.119.4.1 · MIT and upstream licenses · NativeAOT graphics backend\nFFmpeg / ffprobe n9.0 · GPL Full build · Standalone programs\nBtbN/FFmpeg-Builds · GPL-3.0 · Windows/Linux static binaries\ndav1d · BSD-2-Clause · Software AV1 decoding\nx264 · GPL-2.0 · H.264 encoding\nlibtheora · BSD-3-Clause · Theora encoding\nlibogg · BSD-3-Clause · Ogg container\nzlib · Zlib · PNG frame-sequence compression\n\nThe Full build is shipped in the with-ffmpeg archive's tools directory, is not embedded in the app, and contains no nonfree components; no-ffmpeg archives require user configuration. Official packages include third-party licenses; corresponding sources, build configuration, and checksums are supplied with each Release.",
        ["Theme"] = "Theme",
        ["Dark"] = "Dark",
        ["Light"] = "Light",
        ["Archives"] = "independent PFS files",
        ["InvalidPaths"] = "Choose valid, different input and output folders.",
        ["Overwrite"] = "Output exists; click Start again to confirm replacement.",
        ["Finished"] = "Conversion complete",
        ["Failed"] = "Conversion failed",
        ["FailureDetails"] = "Failure details",
        ["ErrorArchive"] = "PFS archive",
        ["ErrorFile"] = "Failed file",
        ["ErrorReason"] = "Error",
        ["Scanning"] = "Scanning…",
        ["NoPfs"] = "No valid PFS archives found.",
        ["StageCopy"] = "Copying project files…",
        ["StageExtract"] = "Extracting PFS…",
        ["StagePack"] = "Rebuilding PFS…",
        ["StageLoose"] = "Processing loose assets…",
        ["StageResource"] = "Converting assets…",
        ["StageComplete"] = "Conversion complete",
        ["DemoProgress"] = "Converting {0} · {1}%"
    };

    public string Language { get; private set; } = "zh-CN";
    public string this[string key] => (Language == "en-US" ? En : Zh).TryGetValue(key, out string? value) ? value : key;
    public event EventHandler? LanguageChanged;

    public void SetLanguage(string language)
    {
        string normalized = language.Equals("en-US", StringComparison.OrdinalIgnoreCase) ? "en-US" : "zh-CN";
        if (normalized == Language) return;
        Language = normalized;
        CultureInfo.CurrentUICulture = CultureInfo.GetCultureInfo(normalized);
        LanguageChanged?.Invoke(this, EventArgs.Empty);
    }

    public static IEnumerable<string> ChineseKeys => Zh.Keys;
    public static IEnumerable<string> EnglishKeys => En.Keys;
}
